# GOOGLE_CLIENT_ID: 27587632278-vji46m6ibej5c0o439p7macjrbhn2s7m.apps.googleusercontent.com

# GOOGLE_CLIENT_SECRET: hxEud4QjbCKZgq0FYCdwAST8
GOOGLE_CLIENT_ID: 96457929887-nt1np0agj3j2dr6k812vuujbsmih09rf.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: GJpgwszIv6AGPceSVp-U-Z7i