development:
  adapter: postgresql
  encoding: unicode
  database: ambitious_development
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ambitious_production
  pool: 5
  username: root
  password: root
  host: localhost  