production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 910879096543-4qhij3fhuop0u59uf6cpm39dh07db69s.apps.googleusercontent.com
  google_client_secret: lk7mrqMnifmC7jS3TJkueJ3QT

test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
