

  development:
  secret_key_base: here_goes_my_secret_key_base
  
  # GOOGLE_CLIENT_ID: 27587632278-vji46m6ibej5c0o439p7macjrbhn2s7m.apps.googleusercontent.com


  # GOOGLE_CLIENT_SECRET: K-dGAWZJghrFxZtXzzZa_UKg


