production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 27587632278-vji46m6ibej5c0o439p7macjrbhn2s7m.apps.googleusercontent.com


  google_client_secret: NiFeWJv0mBamtJ4Hn0eccBww


test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
